AWSTemplateFormatVersion: 2010-09-09
Description: WordPress evolution shared EFS content storage.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  AppSubnetAId:
    Type: AWS::EC2::Subnet::Id
  AppSubnetBId:
    Type: AWS::EC2::Subnet::Id
  AppSubnetCId:
    Type: AWS::EC2::Subnet::Id

Resources:
  SGEFS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow NFS from the WordPress lab VPC
      SecurityGroupIngress:
        - Description: Allow NFS from WordPress lab VPC
          IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 10.125.0.0/16
      Tags:
        - Key: Name
          Value: efs-sg

  WordpressEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      Encrypted: false
      ThroughputMode: bursting
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: wordpress-efs

  MountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref WordpressEFS
      SubnetId: !Ref AppSubnetAId
      SecurityGroups:
        - !Ref SGEFS

  MountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref WordpressEFS
      SubnetId: !Ref AppSubnetBId
      SecurityGroups:
        - !Ref SGEFS

  MountTargetC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref WordpressEFS
      SubnetId: !Ref AppSubnetCId
      SecurityGroups:
        - !Ref SGEFS

Outputs:
  EfsId:
    Value: !Ref WordpressEFS
  EfsSecurityGroupId:
    Value: !Ref SGEFS
