AWSTemplateFormatVersion: 2010-09-09
Description: WordPress evolution RDS MySQL database.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  DbSubnetAId:
    Type: AWS::EC2::Subnet::Id
  DbSubnetBId:
    Type: AWS::EC2::Subnet::Id
  DbSubnetCId:
    Type: AWS::EC2::Subnet::Id
  DBNameValue:
    Type: String
    Default: wordpressdb
  DBUserValue:
    Type: String
    Default: wordpressuser

Resources:
  SGDatabase:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow MySQL from the lab VPC
      SecurityGroupIngress:
        - Description: Allow MySQL from the WordPress lab VPC
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.125.0.0/16
      Tags:
        - Key: Name
          Value: database-sg

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group for WordPress
      SubnetIds:
        - !Ref DbSubnetAId
        - !Ref DbSubnetBId
        - !Ref DbSubnetCId
      Tags:
        - Key: Name
          Value: WordPressRDSSubnetGroup

  RDSinstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      Engine: mysql
      EngineVersion: '8.4.8'
      DBName: !Ref DBNameValue
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp3
      MultiAZ: false
      MasterUsername: !Ref DBUserValue
      MasterUserPassword: '{{resolve:ssm-secure:/Wordpress/DBPassword}}'
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref SGDatabase
      PubliclyAccessible: false

Outputs:
  DBEndpointAddress:
    Value: !GetAtt RDSinstance.Endpoint.Address
  DBEndpointPort:
    Value: !GetAtt RDSinstance.Endpoint.Port
  DatabaseSecurityGroupId:
    Value: !Ref SGDatabase
