AWSTemplateFormatVersion: 2010-09-09
Description: WordPress evolution shared network - public subnets for stage 1.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.125.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 'vpc-${AWS::Region}'

  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true

  SubnetPublicA:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.125.0.0/20
      MapPublicIpOnLaunch: true
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Sub
        - '${VpcPart}${SubnetPart}'
        - VpcPart: !Select [0, !Split ['00::/56', !Select [0, !GetAtt VPC.Ipv6CidrBlocks]]]
          SubnetPart: '00::/64'
      Tags:
        - Key: Name
          Value: sn-public-A

  SubnetPublicB:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.125.16.0/20
      MapPublicIpOnLaunch: true
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Sub
        - '${VpcPart}${SubnetPart}'
        - VpcPart: !Select [0, !Split ['00::/56', !Select [0, !GetAtt VPC.Ipv6CidrBlocks]]]
          SubnetPart: '01::/64'
      Tags:
        - Key: Name
          Value: sn-public-B

  SubnetPublicC:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: 10.125.32.0/20
      MapPublicIpOnLaunch: true
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Sub
        - '${VpcPart}${SubnetPart}'
        - VpcPart: !Select [0, !Split ['00::/56', !Select [0, !GetAtt VPC.Ipv6CidrBlocks]]]
          SubnetPart: '02::/64'
      Tags:
        - Key: Name
          Value: sn-public-C

  SubnetDbA:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.125.48.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Sub
        - '${VpcPart}${SubnetPart}'
        - VpcPart: !Select [0, !Split ['00::/56', !Select [0, !GetAtt VPC.Ipv6CidrBlocks]]]
          SubnetPart: '03::/64'
      Tags:
        - Key: Name
          Value: sn-db-A

  SubnetDbB:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.125.64.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Sub
        - '${VpcPart}${SubnetPart}'
        - VpcPart: !Select [0, !Split ['00::/56', !Select [0, !GetAtt VPC.Ipv6CidrBlocks]]]
          SubnetPart: '04::/64'
      Tags:
        - Key: Name
          Value: sn-db-B

  SubnetDbC:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: 10.125.80.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Sub
        - '${VpcPart}${SubnetPart}'
        - VpcPart: !Select [0, !Split ['00::/56', !Select [0, !GetAtt VPC.Ipv6CidrBlocks]]]
          SubnetPart: '05::/64'
      Tags:
        - Key: Name
          Value: sn-db-C

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub 'igw-${AWS::Region}'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RTPublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub 'vpc-rt-public-${AWS::Region}'

  RTPublicDefaultIPv4:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref RTPublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RTPublicDefaultIPv6:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref RTPublic
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref InternetGateway

  RTAssociationPubA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublicA
      RouteTableId: !Ref RTPublic

  RTAssociationPubB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublicB
      RouteTableId: !Ref RTPublic

  RTAssociationPubC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublicC
      RouteTableId: !Ref RTPublic

Outputs:
  VpcId:
    Value: !Ref VPC
  PublicSubnetAId:
    Value: !Ref SubnetPublicA
  PublicSubnetBId:
    Value: !Ref SubnetPublicB
  PublicSubnetCId:
    Value: !Ref SubnetPublicC
  DbSubnetAId:
    Value: !Ref SubnetDbA
  DbSubnetBId:
    Value: !Ref SubnetDbB
  DbSubnetCId:
    Value: !Ref SubnetDbC
