AWSTemplateFormatVersion: 2010-09-09
Description: WordPress evolution fixed shared SSM parameters for stage 1.

Parameters:
  DBNameValue:
    Type: String
    Default: wordpressdb
  DBUserValue:
    Type: String
    Default: wordpressuser
  DBEndpointValue:
    Type: String
    Default: localhost

Resources:
  DBName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Wordpress/DBName
      Description: WordPress database name
      Type: String
      Value: !Ref DBNameValue

  DBUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Wordpress/DBUser
      Description: WordPress database user
      Type: String
      Value: !Ref DBUserValue

  DBEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Wordpress/DBEndpoint
      Description: WordPress database endpoint. Stage 1 uses local MariaDB.
      Type: String
      Value: !Ref DBEndpointValue

Outputs:
  DBNameParameterName:
    Value: !Ref DBName
  DBUserParameterName:
    Value: !Ref DBUser
  DBEndpointParameterName:
    Value: !Ref DBEndpoint
